#ifndef __UV_K5_PINOUT_
#define __UV_K5_PINOUT_

#include "dp32f030_gpio.h"
#include "dp32f030_map.h"

// Display
#define UVK5_LCD_PORT GPIOB_BASE
#define UVK5_LCD_SPI_PORT SPI0_BASE
#define UVK5_LCD_RST_PIN GPIO_Pin_11
#define UVK5_LCD_A0_PIN GPIO_Pin_9
#define UVK5_LCD_BACKLIGHT_PIN GPIO_Pin_6

// BK4819
#define UVK5_RFIC_PORT GPIOC_BASE
#define UVK5_RFIC_CS_PIN GPIO_Pin_0
#define UVK5_RFIC_CLK_PIN GPIO_Pin_1
#define UVK5_RFIC_DIO_PIN GPIO_Pin_2
#define UVK5_RFIC_ENABLE_PIN GPIO_Pin_4  // Maybe
#define UVK5_RFIC_GPIO_RX_ENABLE 0 // Maybe
#define UVK5_RFIC_GPIO_BAND_VHF 3  // Maybe
#define UVK5_RFIC_GPIO_BAND_UHF 4  // Maybe

// BK1080
#define UVK5_FMR_PORT GPIOA_BASE
#define UVK5_FMR_SCL_PIN GPIO_Pin_10
#define UVK5_FMR_SDA_PIN GPIO_Pin_11

// Keypad
#define UVK5_KEYPAD_PORT GPIOA_BASE
#define UVK5_KEYPAD_ROW_0_PIN GPIO_Pin_3
#define UVK5_KEYPAD_ROW_1_PIN GPIO_Pin_4
#define UVK5_KEYPAD_ROW_2_PIN GPIO_Pin_5
#define UVK5_KEYPAD_ROW_3_PIN GPIO_Pin_6
#define UVK5_KEYPAD_COL_0_PIN GPIO_Pin_10
#define UVK5_KEYPAD_COL_1_PIN GPIO_Pin_11
#define UVK5_KEYPAD_COL_2_PIN GPIO_Pin_12
#define UVK5_KEYPAD_COL_3_PIN GPIO_Pin_13

// PTT
#define UVK5_PTT_KEY_PORT GPIOC_BASE
#define UVK5_PTT_KEY_PIN GPIO_Pin_5

// Flashlight
#define UVK5_FLASHLIGHT_PORT GPIOC_BASE
#define UVK5_FLASHLIGHT_PIN GPIO_Pin_3

// Speech IC
#define UVK5_SPEECH_PORT GPIOA_BASE
#define UVK5_SPEECH_CLK_PIN GPIO_Pin_13
#define UVK5_SPEECH_DATA_PIN GPIO_Pin_12

#endif
